workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Create Flutter Project Structure
        script: |
          flutter create . --org com.madar.app --platforms android
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
